name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0

      - name: Install yarn
        run: npm install yarn -g
      
      - name: Install dependencies
        run: yarn install
      
      - name: Build
        run: yarn run build
      
      - name: Shush jekyll
        run: touch build/.nojekyll
      
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}